version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: listdapp
      POSTGRES_USER: listdapp
      POSTGRES_DB: listdapp
    ports:
      - 5434:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data